### ISSUE TITLE
BleManagerCentralManagerWillRestoreState not working as expected

### ISSUE THREAD

**Issue by gregg062** [innoveit/react-native-ble-manager#1035]
I am trying to implement willRestoreState so that my app can wake up in the background by my peripherals event when it has been suspended, but I am unable to get BleManagerCentralManagerWillRestoreState to work, I have implemented a restoreIdentifierKey
```
 BleManager.start({
      showAlert: false,
      restoreIdentifierKey: 'TreeInTheBackground',
    })
```

and added a listener for events

```
bleManagerEmitter.addListener(
      'BleManagerCentralManagerWillRestoreState',
      async (data: any) => {
        console.log('BleManagerCentralManagerWillRestoreState', data)
          notifee.displayNotification({
            title: 'BLE WillRestoreState',
            body: JSON.stringify(data),
          })
      },
    )
```
I have also allowed background permission and added the necessary info to the info.plist

But when my peripheral sends out an event after being disconnected BleManagerCentralManagerWillRestoreState is never called.

I am currently testing this by toggling on/off airplane mode, I have ensured bluetooth is not toggled off when I toggle on airplane mode. 

Has anyone been able to get willRestoreState to work?

**Comment by MahmoudNafiseh** [comment]
Did you end up figuring this out? Would appreciate any help

**Comment by gregg062** [comment]
@Oyveloper i have had that happen on occasion as well, unfortunately I haven't been able to find a solution....yet.

**Comment by Oyveloper** [comment]
We have noticed that the callback is only called after you first call `BleManager.start` and `BleManager.checkState` again when the app wakes up. We have been able to reliably wake the app up and receive the willRestoreState callback, but we do not get any events on updated characteristics (we get them when in foreground)
When we start up in background now it seems that `retrieveServices` and `startNotification` just hang, and eventually the execution times out …

**Comment by MahmoudNafiseh** [comment]
@marcosinigaglia Is it possible to look into this please?

**Comment by Oyveloper** [comment]
We have managed to get a somewhat working solution. Our app now correctly wakes up when the connected device sends an update on a characteristic, or when it connects/disconnects with the device. The steps we found to work is the following:

1. When the app wakes, set up all listeners on the bleManagerEmitter. 
2. Call `BleManager.start()` and `BleManager.checkState()`. We observed that the `willRestoreState` callback is triggered as soon as we call `checkState`
3. Always call connect on the device, even if BleManager says it is connected. 
4. Do not call `retrieveServices` and `startNotification` if the device was not wakened due to a new connection. We observed that this is where our app started to hang and therefore timed out eventually. 

Further, we notice that when the app is wakened up because of a notification on a characteristic, our listener on value changes is not called for that event. We suspect that this is because our listener to the bleManagerEmitter is not able to be set up early enough, and the event is therefore lost there, even though it probably makes its way to the delegate method implemented by the native module. However, subsequent notifications are received.

**Comment by Oyveloper** [comment]
We found a solution that worked for us, by simply adding the BleManager as the delegate for the peripheral during the `willRestoreState` callback. Added a fix in #1083

**Comment by cheehieu** [comment]
@Oyveloper, nice work! Can you elaborate more on how you went about testing this? Does it relaunch the app in the background and trigger `willRestoreState` in all cases as described in the [developer docs](https://developer.apple.com/documentation/technotes/tn3115-bluetooth-state-restoration-app-relaunch-rules)?

I'm trying to get this working in my app, but it has been difficult to test. Did you restart your device to see `willRestoreState` triggered? Or wait (hours, days??) until iOS kills the app?

**Comment by Oyveloper** [comment]
@cheehieu The easiest way of testing this is to enable `Fast App Terminiation` under developer settings on your iPhone. This makes it so that iOS sends your app into the `killed` state after ~10s, as opposed to ~8hours which is more typical. Note that there are two "killed" states in iOS. One is when the user actively removes your app using the app switcher. You will not receive events in this case. The other case is when iOS kills your app to save energy.

With this setup you can leave your app in the background for around 10s and then trigger some BLE event (disconnect, Characteristic event etc.) 
Your app will then be woken up, and the willRestoreState should be called (as long as you ensure that you subscribe to these events as soon as the app wakes)
It should also trigger any listeners for characteristic updates etc. 

Note: testing this while the app is connected to Metro has been very problematic for us. The issue seems that it then initiates a new bundle, and simply spends too much time. In order to test this better we made a setup where we log everything that happens to `AsyncStorage` so that we can test while disconnected from Metro, but still retrieve the log afterwards for troubleshooting.

**Comment by vhakulinen** [comment]
Did any of you get the restore events to land on the javascript event listeners?

I noticed that the actual event wasn't emitted to the `RCTEventEmitter` but instead to `NSNotificationCenter`. You could receive these events from native code but not from js.

I made #1282 to fix this.
