### ISSUE TITLE
IOS | how to read data more than 512 bytes using BLE react native. now we can read only 512 bytes of data

### ISSUE THREAD

**Issue by yoginitheesh** [innoveit/react-native-ble-manager#441]
### Version

Tell us which versions you are using:

- react-native-ble-manager v?.?.?
- react-native v?.?
- iOS/Android v.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi, you have to split your data and handle this "queue" by your app.

**Comment by yoginitheesh** [comment]
@marcosinigaglia  Scenarios: 1- After sending write request m sending one read request ,that time m getting only 512 bytes of data. but actual size is more than 512 bytes. again no need to send read request to read remaining data rite? . In android its was working fine. In IOs m getting this issue. Any suggestions?

**Comment by marcosinigaglia** [comment]
I think Is better to use the notification so you can have multiple notifications after your write.

**Comment by yoginitheesh** [comment]
Thanks @marcosinigaglia. Let me check.

**Comment by sushanthNiveus** [comment]
@marcosinigaglia Hi Marc. Facing the same issue here. Sending the same data to both Android and iOS. In Android complete data is read properly but in iOS data is truncated. If the issue is on BLE peripheral side, data wouldn't have sent to Android also.  Any idea?
![screenshot 2019-01-22 at 4 18 04 pm](https://user-images.githubusercontent.com/13234541/51531030-54cf2280-1e62-11e9-8f70-0ffa6d01939d.png)

**Comment by marcosinigaglia** [comment]
Hi @sushanthNiveus , is not an issue, is an OS specification, you have to hadle it manually.
