### ISSUE TITLE
getConnectedPeripherals type error

### ISSUE THREAD

**Issue by OrLevy23** [innoveit/react-native-ble-manager#506]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.1
- react-native v0.58
- iOS/Android v. iOS

### Expected behaviour
getConnectedPeripherals has wrong return type (typescript)
the return value suppose promise with array of peripherals but instead it says:

```
Promise<void>
```

**Comment by wangrenhai** [comment]
Dear author,


I would like to ask why once my SDK version exceeds 22, bluetooth can not be searched, I have been very troubled, if you can help me solve, I am very grateful...





------------------ 原始邮件 ------------------
发件人: "OrLevy23"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午5:24
收件人: "innoveit/react-native-ble-manager"<react-native-ble-manager@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [innoveit/react-native-ble-manager] getConnectedPeripherals typeerror (#506)




Version
 
Tell us which versions you are using:
  
react-native-ble-manager v6.6.1
 
react-native v0.58
 
iOS/Android v. iOS
  
Expected behaviour
 
getConnectedPeripherals has wrong return type (typescript)
 the return value suppose promise with array of peripherals but instead

**Comment by marcosinigaglia** [comment]
Hi @OrLevy23 , can you check if you have the error only when there aren't connected peripherals?

**Comment by OrLevy23** [comment]
@marcosinigaglia, the problem is with the types (TS) of the native module, when looked at the native module i saw that the return value is callback of array of peripherals, but the types file says that the return value is ``` Promise<void>```

**Comment by marcosinigaglia** [comment]
I don't use TS but in https://github.com/innoveit/react-native-ble-manager/blob/master/index.d.ts file I see `Promise<any[]>`.
