### ISSUE TITLE
Is it possible to do the same about the react-native-ble-lx?

### ISSUE THREAD

**Issue by vagnerwentz** [innoveit/react-native-ble-manager#662]
I have a question, I'm not really enjoying react-native-ble-plx, their documentation is not very good ... And I would like to know if I can scan Bluetooth, connect with the module that has a specific name, be able to send and receive data using react-native-ble-manager

**Comment by marcosinigaglia** [comment]
I never used the library, I think is similar.

**Comment by vagnerwentz** [comment]
> I never used the library, I think is similar.

Hi Marcos, how are you? I tried to use with TypeScript but the example that the library gives I did not understand and do not have the option to clone.

**Comment by RRMoelker** [comment]
We're in the process of switching out `react-native-ble-plx` to this because the other library does not return the connected devices for Android (bug).

So far this library is able to match the features of the other library. And it works very well.

Some notes:
* There a quite a few silent failures in this library. So error handling is harder. e.g.:
  * Starting scan when Bluetooth is off.
  * Sending large data packets without specifying max bytes silently failed in our case.
* There isn't a notion of a "Device" such as in the other library. You'll need to pass the device id everywhere yourself. It's nice not having two ways to do the same thing.
* The scan is for a limited duration (no need to add that yourself)
* The TypeScript typings aren't always accurate it seems.
* If you end up using this, don't forget to write Arrays, not Uint8Arrays. The latter will fail unexpectedly.

**Comment by vagnerwentz** [comment]
I done what I wanted
