### ISSUE TITLE
Could not read data from flic2 device

### ISSUE THREAD

**Issue by khushalt10** [innoveit/react-native-ble-manager#921]
Hi,

We are trying to communicate with [Flic2](https://flic.io/) BLE device on android, we were able to connect to the device and retrieve following characteristics 

`[{"characteristic": "2a00", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2a01", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2a05", "descriptors": [[Object]], "properties": {"Indicate": "Indicate"}, "service": "1801"}, {"characteristic": "00420001-8f59-4420-870d-84f3b617e493", "properties": {"WriteWithoutResponse": "WriteWithoutResponse"}, "service": "00420000-8f59-4420-870d-84f3b617e493"}, {"characteristic": "00420002-8f59-4420-870d-84f3b617e493", "descriptors": [[Object]], "properties": {"Notify": "Notify"}, "service": "00420000-8f59-4420-870d-84f3b617e493"}]`

We have tried both `read` and `startNotification` methods and also managed to get the response `[101]` , but on device click the `BleManagerDidUpdateValueForCharacteristic` is not receiving any data

We were able to read the actions for itag BLE device, but not able to same with flic2. please let us know if this is an issue regarding device or your package.

Thanks

**Comment by iam-aman** [comment]
Hi @marcosinigaglia @khushalt10 

I'm using this package as well in order to connect to a flic2 button and receive data on button clicks. The connection was successful but i'm unable to receive data . Tried using the 'BleManagerDidUpdateValueForCharacteristic' event listener.

I see this task has been closed last week. If you were able to find a solution for it, can you please provide some information on it.

Thanks
